repos:
  # isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python imports)

  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 (python linter)
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
          - flake8-pydantic
          - flake8-annotations
          - flake8-absolute-import

  # pylint
  - repo: local
    hooks:
      - id: pylint
        name: pylint (score >= 9.0 required)
        entry: pylint
        language: system
        types: [ python ]
        args:
          - "--fail-under=9.0"
