# -*- coding: utf-8 -*-

"""CIDOC CRM properties package;

"""


from pyheritage.cidoc.core.properties._actors import (
    P74HasCurrentOrFormerResidence,
    P75Possesses,
    P76HasContactPoint,
    P107HasCurrentOrFormerMember,
    P152HasParent,
)
from pyheritage.cidoc.core.properties._conceptual import (
    P67RefersTo,
    P68ForeseesUseOf,
    P69HasAssociationWith,
    P70Documents,
    P71Lists,
    P72HasLanguage,
    P73HasTranslation,
    P104IsSubjectTo,
    P105RightHeldBy,
    P106IsComposedOf,
    P129IsAbout,
    P138Represents,
    P148HasComponent,
    P165Incorporates,
    P187HasProductionPlan,
    P188RequiresProductionTool,
)
from pyheritage.cidoc.core.properties._identification import (
    P1IsIdentifiedBy,
    P2HasType,
    P3HasNote,
    P48HasPreferredIdentifier,
    P102HasTitle,
    P127HasBroaderTerm,
    P137Exemplifies,
    P139HasAlternativeForm,
    P150DefinesTypicalPartsOf,
    P190HasSymbolicContent,
)
from pyheritage.cidoc.core.properties._physical import (
    P43HasDimension,
    P44HasCondition,
    P45ConsistsOf,
    P46IsComposedOf,
    P49HasFormerOrCurrentKeeper,
    P50HasCurrentKeeper,
    P51HasCurrentOrFormerOwner,
    P52HasCurrentOwner,
    P53HasFormerOrCurrentLocation,
    P54HasCurrentPermanentLocation,
    P55HasCurrentLocation,
    P56BearsFeature,
    P57HasNumberOfParts,
    P59HasSection,
    P62Depicts,
    P65ShowsVisualItem,
    P101HadAGeneralUse,
    P103WasIntendedFor,
    P109HasCurrentOrFormerCurator,
    P128Carries,
    P130ShowsFeaturesOf,
    P156Occupies,
    P196Defines,
    PxxxHoldsOrSupports,
)
from pyheritage.cidoc.core.properties._spacetime import (
    P79BeginningIsQualifiedBy,
    P80EndIsQualifiedBy,
    P81OngoingThroughout,
    P82AtSomeTimeWithin,
    P86FallsWithin,
    P89FallsWithin,
    P90HasValue,
    P91HasUnit,
    P121OverlapsWith,
    P122BordersWith,
    P132SpatiotemporallyOverlaps,
    P133IsSpatiotemporallySeparated,
    P157IsAtRestRelativeTo,
    P160HasTemporalProjection,
    P161HasSpatialProjection,
    P164During,
    P166WasAPresenceOf,
    P167At,
    P168PlaceIsDefinedBy,
    P169DefinesSpacetimeVolume,
    P170DefinesTime,
    P171AtSomePlaceWithin,
    P172Contains,
    P180HasCurrency,
    P181HasAmount,
    P189Approximates,
    P191HadDuration,
    P195WasAPresenceOf,
    P197CoveredPartsOf,
)
from pyheritage.cidoc.core.properties._temporal import (
    P4HasTimeSpan,
    P5ConsistsOf,
    P7TookPlaceAt,
    P8TookPlaceOnOrWithin,
    P9ConsistsOf,
    P10FallsWithin,
    P11HadParticipant,
    P12OccurredInPresenceOf,
    P13Destroyed,
    P14CarriedOutBy,
    P15WasInfluencedBy,
    P16UsedSpecificObject,
    P17WasMotivatedBy,
    P19WasIntendedUseOf,
    P20HadSpecificPurpose,
    P21HadGeneralPurpose,
    P22TransferredTitleTo,
    P23TransferredTitleFrom,
    P24TransferredTitleOf,
    P25Moved,
    P26MovedTo,
    P27MovedFrom,
    P28CustodySurrenderedBy,
    P29CustodyReceivedBy,
    P30TransferredCustodyOf,
    P31HasModified,
    P32UsedGeneralTechnique,
    P33UsedSpecificTechnique,
    P34Concerned,
    P35Identified,
    P37Assigned,
    P38Deassigned,
    P39Measured,
    P40ObservedDimension,
    P41Classified,
    P42Assigned,
    P92BroughtIntoExistence,
    P93TookOutOfExistence,
    P94HasCreated,
    P95HasFormed,
    P96ByMother,
    P97FromFather,
    P98BroughtIntoLife,
    P99Dissolved,
    P100WasDeathOf,
    P108HasProduced,
    P110Augmented,
    P111Added,
    P112Diminished,
    P113Removed,
    P123ResultedIn,
    P124Transformed,
    P125UsedObjectOfType,
    P126Employed,
    P134Continued,
    P135CreatedType,
    P136WasBasedOn,
    P140AssignedAttributeTo,
    P141Assigned,
    P142UsedConstituent,
    P143Joined,
    P144JoinedWith,
    P145Separated,
    P146SeparatedFrom,
    P147Curated,
    P151WasFormedFrom,
    P173StartsBeforeOrWithTheEndOf,
    P174StartsBeforeTheEndOf,
    P175StartsBeforeOrWithTheStartOf,
    P176StartsBeforeTheStartOf,
    P177AssignedPropertyType,
    P179HadSalesPrice,
    P182EndsBeforeOrWitheStartOf,
    P183EndsBeforeTheStartOf,
    P184EndsBeforeOrWithTheEndOf,
    P185EndsBeforeTheEndOf,
    P186ProducedThingOfProductType,
)


__all__ = ('P1IsIdentifiedBy', 'P2HasType', 'P3HasNote', 'P4HasTimeSpan', 'P5ConsistsOf', 'P7TookPlaceAt',
           'P8TookPlaceOnOrWithin', 'P9ConsistsOf', 'P10FallsWithin', 'P11HadParticipant', 'P12OccurredInPresenceOf',
           'P13Destroyed', 'P14CarriedOutBy', 'P15WasInfluencedBy', 'P16UsedSpecificObject', 'P17WasMotivatedBy',
           'P19WasIntendedUseOf', 'P20HadSpecificPurpose', 'P21HadGeneralPurpose', 'P22TransferredTitleTo',
           'P23TransferredTitleFrom', 'P24TransferredTitleOf', 'P25Moved', 'P26MovedTo', 'P27MovedFrom',
           'P28CustodySurrenderedBy', 'P29CustodyReceivedBy', 'P30TransferredCustodyOf', 'P31HasModified',
           'P32UsedGeneralTechnique', 'P33UsedSpecificTechnique', 'P34Concerned', 'P35Identified', 'P37Assigned',
           'P38Deassigned', 'P39Measured', 'P40ObservedDimension', 'P41Classified', 'P42Assigned', 'P43HasDimension',
           'P44HasCondition', 'P45ConsistsOf', 'P46IsComposedOf', 'P48HasPreferredIdentifier',
           'P49HasFormerOrCurrentKeeper', 'P50HasCurrentKeeper', 'P51HasCurrentOrFormerOwner', 'P52HasCurrentOwner',
           'P53HasFormerOrCurrentLocation', 'P54HasCurrentPermanentLocation', 'P55HasCurrentLocation',
           'P56BearsFeature', 'P57HasNumberOfParts', 'P59HasSection', 'P62Depicts', 'P65ShowsVisualItem',
           'P67RefersTo', 'P68ForeseesUseOf', 'P69HasAssociationWith', 'P70Documents', 'P71Lists', 'P72HasLanguage',
           'P73HasTranslation', 'P74HasCurrentOrFormerResidence', 'P75Possesses', 'P76HasContactPoint',
           'P79BeginningIsQualifiedBy', 'P80EndIsQualifiedBy', 'P81OngoingThroughout', 'P82AtSomeTimeWithin',
           'P86FallsWithin', 'P89FallsWithin', 'P90HasValue', 'P91HasUnit', 'P92BroughtIntoExistence',
           'P93TookOutOfExistence', 'P94HasCreated', 'P95HasFormed', 'P96ByMother', 'P97FromFather',
           'P98BroughtIntoLife', 'P99Dissolved', 'P100WasDeathOf', 'P101HadAGeneralUse', 'P102HasTitle',
           'P103WasIntendedFor', 'P104IsSubjectTo', 'P105RightHeldBy', 'P106IsComposedOf',
           'P107HasCurrentOrFormerMember', 'P108HasProduced', 'P109HasCurrentOrFormerCurator', 'P110Augmented',
           'P111Added', 'P112Diminished', 'P113Removed', 'P121OverlapsWith', 'P122BordersWith', 'P123ResultedIn',
           'P124Transformed', 'P125UsedObjectOfType', 'P126Employed', 'P127HasBroaderTerm', 'P128Carries',
           'P129IsAbout', 'P130ShowsFeaturesOf', 'P132SpatiotemporallyOverlaps', 'P133IsSpatiotemporallySeparated',
           'P134Continued', 'P135CreatedType', 'P136WasBasedOn', 'P137Exemplifies', 'P138Represents',
           'P139HasAlternativeForm', 'P140AssignedAttributeTo', 'P141Assigned', 'P142UsedConstituent', 'P143Joined',
           'P144JoinedWith', 'P145Separated', 'P146SeparatedFrom', 'P147Curated', 'P148HasComponent',
           'P150DefinesTypicalPartsOf', 'P151WasFormedFrom', 'P152HasParent', 'P156Occupies',
           'P157IsAtRestRelativeTo', 'P160HasTemporalProjection', 'P161HasSpatialProjection', 'P164During',
           'P165Incorporates', 'P166WasAPresenceOf', 'P167At', 'P168PlaceIsDefinedBy', 'P169DefinesSpacetimeVolume',
           'P170DefinesTime', 'P171AtSomePlaceWithin', 'P172Contains', 'P173StartsBeforeOrWithTheEndOf',
           'P174StartsBeforeTheEndOf', 'P175StartsBeforeOrWithTheStartOf', 'P176StartsBeforeTheStartOf',
           'P177AssignedPropertyType', 'P179HadSalesPrice', 'P180HasCurrency', 'P181HasAmount',
           'P182EndsBeforeOrWitheStartOf', 'P183EndsBeforeTheStartOf', 'P184EndsBeforeOrWithTheEndOf',
           'P185EndsBeforeTheEndOf', 'P186ProducedThingOfProductType', 'P187HasProductionPlan',
           'P188RequiresProductionTool', 'P189Approximates', 'P190HasSymbolicContent', 'P191HadDuration',
           'P195WasAPresenceOf', 'P196Defines', 'P197CoveredPartsOf', 'PxxxHoldsOrSupports', )
